/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainFrame;

import Transaksi.TransaksiForm;
import helm.DataHelmForm;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import login.LoginForm;
import javax.swing.JOptionPane;
import login.LoginDAO;
import login.LoginDAOImp;
import pembelian.PembelianForm;
import penjualan.PenjualanForm;
import supplier.SupplierForm;
import user.UserForm;
import login.Login;
/**
 *
 * @author dex
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        menuhelm.setVisible(false);
        menulogout.setVisible(false);
        menusupplier.setVisible(false);
        menutransaksi.setVisible(false);
        menuuser.setVisible(false);
        menUser.setText("USER : ----  ");
        tanggal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menulogin = new javax.swing.JMenu();
        menulogout = new javax.swing.JMenuItem();
        menulogin1 = new javax.swing.JMenuItem();
        menuuser = new javax.swing.JMenuItem();
        menusupplier = new javax.swing.JMenuItem();
        menuhelm = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        menutransaksi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menUser = new javax.swing.JMenu();
        MenuTanggal = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainFrame/6b2e986ece3a781127cfc167e0144e3c.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        menulogin.setText("AKUN");

        menulogout.setText("LOG OUT");
        menulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogoutActionPerformed(evt);
            }
        });
        menulogin.add(menulogout);

        menulogin1.setText("LOGIN");
        menulogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menulogin1ActionPerformed(evt);
            }
        });
        menulogin.add(menulogin1);

        menuuser.setText("KELOLA USER");
        menuuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuuserActionPerformed(evt);
            }
        });
        menulogin.add(menuuser);

        menusupplier.setText("KELOLA SUPPLIER");
        menusupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusupplierActionPerformed(evt);
            }
        });
        menulogin.add(menusupplier);

        jMenuBar1.add(menulogin);

        menuhelm.setText("DATA HELM");

        jMenuItem8.setText("TAMBAH DATA HELM");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuhelm.add(jMenuItem8);

        jMenuBar1.add(menuhelm);

        menutransaksi.setText("TRANSAKSI");

        jMenuItem1.setText("PENJUALAN HELM");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menutransaksi.add(jMenuItem1);

        jMenuItem2.setText("PEMBELIAN HELM");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menutransaksi.add(jMenuItem2);

        jMenuItem3.setText("DAFTAR TRANSAKSI ALL TIME");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menutransaksi.add(jMenuItem3);

        jMenuBar1.add(menutransaksi);

        jMenu1.setText("                                           ");
        jMenuBar1.add(jMenu1);

        menUser.setText("USER");
        jMenuBar1.add(menUser);

        MenuTanggal.setText("TANGGAL");
        jMenuBar1.add(MenuTanggal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PenjualanForm p = new PenjualanForm();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PembelianForm p=new PembelianForm();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        DataHelmForm d = new DataHelmForm();
        d.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuuserActionPerformed
        UserForm u = new UserForm();
        u.setVisible(true);
    }//GEN-LAST:event_menuuserActionPerformed

    private void menusupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusupplierActionPerformed
        SupplierForm s = new SupplierForm();
        s.setVisible(true);
    }//GEN-LAST:event_menusupplierActionPerformed

    private void menulogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulogin1ActionPerformed
        LoginForm l = new LoginForm();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_menulogin1ActionPerformed

    private void menulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menulogoutActionPerformed
        LoginDAO l = new LoginDAOImp();
        l.logout();
        menuhelm.setVisible(false);
        menulogout.setVisible(false);
        menusupplier.setVisible(false);
        menutransaksi.setVisible(false);
        menuuser.setVisible(false);
        menulogin1.setVisible(true);
        menUser.setText("USER : ----");
        JOptionPane.showMessageDialog(null, "log out berhasil");
        
    }//GEN-LAST:event_menulogoutActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TransaksiForm t = new TransaksiForm();
        t.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JMenu menUser;
    public static javax.swing.JMenu menuhelm;
    private javax.swing.JMenu menulogin;
    public static javax.swing.JMenuItem menulogin1;
    public static javax.swing.JMenuItem menulogout;
    public static javax.swing.JMenuItem menusupplier;
    public static javax.swing.JMenu menutransaksi;
    public static javax.swing.JMenuItem menuuser;
    // End of variables declaration//GEN-END:variables
    private void tanggal(){
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
    MenuTanggal.setText(String.valueOf("TANGGAL : "+dateFormat.format(date)));
    }
}
